# Generated by Django 3.1.3 on 2021-02-03 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('journal', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('pmid', models.CharField(max_length=10)),
            ],
        ),
    ]
