# Generated by Django 3.1.6 on 2021-03-02 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='category',
            field=models.CharField(choices=[('ADIPOSE', 'Adipose Progenitor Cell Heterogeneity'), ('PROTEOMICS', 'Advances in Proteomics')], default='ADIPOSE', max_length=10),
        ),
    ]
