# Generated by Django 3.2.6 on 2021-09-30 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pathology_tr',
            name='surgical_margin',
            field=models.CharField(choices=[('0 No residual tumor', '0 No residual tumor'), ('1 Residual tumor, NOS', '1 Residual tumor, NOS'), ('2 Microscopic residual tumor', '2 Microscopic residual tumor'), ('3 Macroscopic residual tumor', '3 Macroscopic residual tumor'), ('7 Margins not evaluable', '7 Margins not evaluable'), ('8 No primary site surgery', '8 No primary site surgery'), ('9 Unknown or not applicable', '9 Unknown or not applicable')], max_length=30),
        ),
        migrations.AlterField(
            model_name='pathology_tr',
            name='tumor_grade',
            field=models.CharField(choices=[('1 Grade I', '1 Grade I'), ('2 Grade II', '2 Grade II'), ('3 Grade III', '3 Grade III'), ('4 Grade IV', '4 Grade IV'), ('6 B-cell', '6 B-cell'), ('9 Grade/differentiation unknown, not stated, or not applicable', '9 Grade/differentiation unknown, not stated, or not applicable')], max_length=70, null=True),
        ),
    ]
