# Generated by Django 3.2.6 on 2021-09-30 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_auto_20210930_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='vital_status',
            field=models.CharField(choices=[('0 Dead (CoC)', '0 Dead (CoC)'), ('1 Alive', '1 Alive')], max_length=20, null=True),
        ),
    ]
