# Generated by Django 3.2.6 on 2022-09-25 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_alter_patient_vital_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='accession',
            field=models.CharField(default='na', max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='uuid',
            field=models.CharField(default='na', max_length=36),
            preserve_default=False,
        ),
    ]
